version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sammogu
    environment:
      POSTGRES_USER: schoolboy
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  